base_regions:
- arm_id: left_arm
  calibration_resolution:
  - 1408
  - 1024
  name: 左区（移栽机）
  polygon_vertices:
  - - 101
    - 218
  - - 589
    - 215
  - - 579
    - 1022
  - - 95
    - 1023
  region_id: left_zone
  sub_regions:
  - edge_vector: null
    layer_index: null
    name: left_area_top
    polygon_vertices:
    - - 157
      - 216
    - - 588
      - 215
    - - 591
      - 298
    - - 157
      - 282
    sub_region_id: left_zone_sub_1768234665863
    type: custom
  - edge_vector: null
    layer_index: null
    name: left_area_left
    polygon_vertices:
    - - 101
      - 223
    - - 179
      - 218
    - - 179
      - 1018
    - - 96
      - 1019
    sub_region_id: left_zone_sub_1768234713870
    type: custom
  - edge_vector: null
    layer_index: null
    name: left_area_right
    polygon_vertices:
    - - 586
      - 214
    - - 682
      - 216
    - - 678
      - 1025
    - - 577
      - 1017
    sub_region_id: left_zone_sub_1768234760224
    type: custom
- arm_id: right_arm
  calibration_resolution:
  - 1408
  - 1024
  name: 右区（传送带）
  polygon_vertices:
  - - 682
    - 221
  - - 1406
    - 212
  - - 1406
    - 1023
  - - 1221
    - 1021
  - - 679
    - 851
  region_id: right_zone
  sub_regions:
  - edge_vector: null
    layer_index: null
    name: right_area_base
    polygon_vertices:
    - - 678
      - 220
    - - 1405
      - 216
    - - 1411
      - 437
    - - 683
      - 301
    sub_region_id: right_zone_sub_1768234797744
    type: custom
  - edge_vector: null
    layer_index: null
    name: right_area_under
    polygon_vertices:
    - - 681
      - 768
    - - 1409
      - 1026
    - - 1221
      - 1019
    - - 676
      - 856
    sub_region_id: right_zone_sub_1768234867786
    type: custom
